spring.application.name=inpromaapp

# Server Port (Note: You are running on 8088)
server.port=8088

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/investment_profile_management
spring.datasource.username=root
spring.datasource.password=inproma@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Finnhub API Key
finnhub.api.key=db28napr01qrufhaf1gdb28napr01qrufhaf20