spring.application.name=inpromaapp
server.port=8088
spring.datasource.url=jdbc:MySQL://localhost:3306/investment_profile_management
spring.datasource.username=root
spring.datasource.password=inproma@123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true